import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/provider";
import { Toaster } from "sonner";
import { icons } from "@/utils/toastIcons";
import { Lobster, Madimi_One } from "next/font/google";

const madimi = Madimi_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-madimi",
});

const lobster = Lobster({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lobster",
});

export const metadata: Metadata = {
  title: "AS Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${madimi.variable} ${lobster.variable}`}>
        <Providers>{children}</Providers>
        <Toaster icons={icons} position="bottom-right" />
      </body>
    </html>
  );
}
